import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable()
export class WasmService {

  constructor(private http: HttpClient) { }

  /**
   * Instantiates a JavaScript loader for WebAssembly, generated by Emscripten
   * 
   * @param url the URL to the generated JavaScript loader
   * @param moduleObj optional module options
   */
  instantiateJs(url: string, moduleObj?: EmModule): Observable<string> {
    const script = document.createElement('script');
    script.async = true;
    document.body.appendChild(script);

    if (moduleObj) {
      window.Module = moduleObj;
    }

    return new Observable<string>(subscriber => {
      script.onload = () => {
        subscriber.next(script.innerHTML);
        subscriber.complete();
      };
      script.onerror = (ev: ErrorEvent) => subscriber.error(ev.error);
      script.src = url;
    });
  }

  /**
   * Instantiates a pure WebAsembly module
   * 
   * @param url the URL to the module
   * @param imports optional imports for the module
   */
  instantiateWasm(url: string, imports?: Object): Observable<WebAssembly.Instance> {
    return this.http.get(url, { responseType: 'arraybuffer' })
      .mergeMap(bytes => WebAssembly.compile(bytes))
      .mergeMap(wasmModule => WebAssembly.instantiate(wasmModule, imports));
  }

  /**
   * Exits the active Emscripten environment by calling exit()
   */
  exitActiveEnvironment() {
    if (!window.Module)
      throw Error('No active Emscripten environment found');

    const mod = window.Module;
    mod.noExitRuntime = false;
    try {
      mod.exit(0);
    }
    catch (err) {
      if (err.name !== 'ExitStatus')
        throw err;
    }
  }

  /**
   * Reads a UTF8 zero-terminated string from the memory
   * 
   * @param heap the memory
   * @param offset a pointer to the memory
   */
  utf8ToString(heap: Uint8Array, offset: number): string {
    let s = '';
    for (let i = offset; heap[i]; i++) {
      s += String.fromCharCode(heap[i]);
    }
    return s;
  }

  /**
   * Creates default imports for a "pure" WemAssembly module without
   * Emscripten's API (but still generated by Emscripten)
   */
  createDefaultImports(): any {
    return {
      env: {
        memoryBase: 0,
        memory: new WebAssembly.Memory({ initial: 256 }),
        tableBase: 0,
        table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' })
      }
    };
  }

  /**
   * Creates a danew data file in the memory
   * 
   * @param fileName the file name 
   * @param inputArray the file contents
   */
  createDataFile(fileName: string, inputArray: Uint8Array, canRead?: boolean, canWrite?: boolean) {
    try {
      FS.createDataFile('/', fileName, inputArray, canRead, canWrite);
    }
    catch (err) {
      if (err.code !== 'EEXIST')
        throw err;
    }
  }

  /**
   * Reads a file from the memory as a text
   * 
   * @param fileName the file name
   */
  readTextFile(fileName: string): string {
    return FS.readFile(fileName, { encoding: 'utf8' });
  }
}